name: CI/CD github-action heroku brief
on:
  push:
    branches: [ dev ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    # access to the repository code
    -uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: lint
      run: npm run lint

    - name: Unit tests
      run: npm run test:ci

  build:
    needs: test
    runs-on: ubuntu-latest

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run build:prod

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: devops-test-${{ github.run_id }}-${{ github.run_number }}
        path: ./dist/devops-test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Dowload artifact
      uses: actions/download-artifact@v2
      with:
        name: devops-test-${{ github.run_id }}-${{ github.run_number }}
        path: './build'

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
